{{- if and (not .Values.database.existingSecret) .Values.database.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gascurve.fullname" . }}-db
  labels:
    {{- include "gascurve.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_URL: {{ .Values.database.url | quote }}
{{- end }}
